exchange:
  name: openalgo

  # OpenAlgo API Configuration
  # Get your API key from OpenAlgo dashboard
  # For testing, you can use a test key or get one from http://127.0.0.1:5000
  apiKey: '6f43b2f2eafd8b5830d6ffe6ff3977a388b9e280a3be36f56e2e5f0918215d83'

  # OpenAlgo host URL (default: local installation)
  hostUrl: 'http://127.0.0.1:5000'

  # Products/Symbols to trade
  # Format: 'SYMBOL': {config}
  products:
    # Index Options
    - 'NFO:BANKNIFTY25NOV2546500PE':
        id: 'BANKNIFTY25NOV2546500PE'
        display_name: 'BANKNIFTY25NOV2546500PE'
        exchange: 'NFO'
        segment: 'FNO'
        instrument_type: 'OPTIDX'
        product_type: 'MIS'  # MIS or NRML
        asset_type: 'OPTIONS'
        fund_type: 'INR'

    - 'NFO:NIFTY30JUN2630000CE':
        id: 'NIFTY30JUN2630000CE'
        display_name: 'NIFTY30JUN2630000CE'
        exchange: 'NFO'
        segment: 'FNO'
        instrument_type: 'OPTIDX'
        product_type: 'MIS'
        asset_type: 'OPTIONS'
        fund_type: 'INR'

    - 'NFO:SBIN28OCT25770PE':
        id: 'SBIN28OCT25770PE'
        display_name: 'SBIN28OCT25770PE'
        exchange: 'NFO'
        segment: 'FNO'
        instrument_type: 'OPTIDX'
        product_type: 'MIS'
        asset_type: 'OPTIONS'
        fund_type: 'INR'

  # Custom lot sizes (optional - overrides defaults)
  # These are already defined in code, but can be customized here
  lot_sizes:
    NIFTY: 50
    BANKNIFTY: 15
    FINNIFTY: 40
    MIDCPNIFTY: 75

  # Backfill configuration
  backfill_enabled: true
  backfill_period: 30  # days

  # Test mode (paper trading)
  test_mode: false
