global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'wolfinch-algoedge'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
        labels:
          service: 'influxdb'

  # Redis metrics via redis_exporter
  - job_name: 'redis-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Kafka JMX metrics
  - job_name: 'kafka-jmx'
    scrape_interval: 30s
    static_configs:
      - targets: ['kafka:9999']
        labels:
          service: 'kafka'

  # PostgreSQL metrics via postgres_exporter
  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Wolfinch application metrics
  - job_name: 'wolfinch-app'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'wolfinch'
          component: 'trading-engine'
