#  Copyright: (c) 2017-2019 Joshith Rayaroth Koderi
#  This file is part of Wolfinch.
# 
#  Wolfinch is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  Wolfinch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with Wolfinch.  If not, see <https://www.gnu.org/licenses/>.
##################################################
# Wolfinch Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
#   - 'binance': 
#      role: 'secondary'
#      config: 'config/binance.yml'
   - 'cbpro' : 
      role: 'primary'
      config: 'config/cbpro_sim.yml'
      products:
         - 'BTC-USD':
            active: true         
            fund_max_liquidity : 900 #$$               
            fund_max_per_buy_value : 30 #$100 max per buy
            asset_max_per_trade_size: 1 #per sell asset size max
            asset_min_per_trade_size: 0.0001 #Min asset size to trade with (may come from exch limits or asset limits)
            stop_loss:
               enabled: true
               kind : trailing      #simple(default) | trailing | ATRXX | 
               rate : 3 #-3%
            take_profit:
               enabled: true
               rate: 6 # 10percent
            decision:
               model    : simple
               config   :
                  strategy: EMA_DEV
                  params : {'ema_sell_s': 85, 'timeout_sell': 14, 'rsi': 24, 'treshold_pct_buy_l': 1.0, 'ema_buy_s': 185, 'timeout_buy': 14, 'period': 165, 'treshold_pct_sell_s': 0.92, 'ema_buy_l': 70, 'treshold_pct_sell_l': 1.35, 'treshold_pct_buy_s': 0.39, 'ema_sell_l': 25}
      # products - end
      order_type    : market
      fee     : 
         maker : 0.5 #make fee %
         taker : 0.5 #taker fee %
   #cbpro - end
# exchanges - end

# TODO: exchanges specific config should follow a common timing, should be driven by global config
candle_interval : 300  #300s == 5m 

backfill:
   enabled  : true  
   period   : 10  #in Days

simulator:
   enabled : false
   backtesting : true
   
genetic_optimizer: 
   enabled : false
   N_POP : 1
   N_GEN : 1
   N_MP : 1
   strategy : EMA_DEV
ui:
   enabled : true
   port : 8080
   
#EOF
