#  Copyright: (c) 2017-2019 Joshith Rayaroth Koderi
#  This file is part of Wolfinch.
# 
#  Wolfinch is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  Wolfinch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with Wolfinch.  If not, see <https://www.gnu.org/licenses/>.
##################################################
# Wolfinch Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
#   - 'binance': 
#      role: 'secondary'
#      config: 'config/binance.yml'
   - 'cbpro' : 
      role: 'primary'
      config: 'config/cbpro.yml'
      products:
         - 'BTC-USD':
            fund_max_liquidity : 1000 #$$               
            fund_max_per_buy_value : 30 #$100 max per buy
            asset_max_per_trade_size: 1 #per sell asset size max
            asset_min_per_trade_size: 0.0001 #Min asset size to trade with (may come from exch limits or asset limits)           
            stop_loss:
               enabled: true
               kind : trailing      #simple(default) | trailing | ATRXX | 
               rate : 6 #-3%
            take_profit:
               enabled: true
               rate: 16 # 10percent
            decision:
               model    : simple
               config   :
                  strategy: EMA_DEV
                  params : {'ema_sell_s': 85, 'timeout_sell': 14, 'rsi': 24, 'treshold_pct_buy_l': 1.0, 'ema_buy_s': 185, 'timeout_buy': 14, 'period': 165, 'treshold_pct_sell_s': 0.92, 'ema_buy_l': 70, 'treshold_pct_sell_l': 1.35, 'treshold_pct_buy_s': 0.39, 'ema_sell_l': 25}
         - 'XLM-USD':
            fund_max_liquidity : 1000 #$$               
            fund_max_per_buy_value : 20 #$100 max per buy
            asset_max_per_trade_size: 100 #per sell asset size max
            asset_min_per_trade_size: 1 #Min asset size to trade with (may come from exch limits or asset limits)      
            stop_loss:
               enabled: true
               kind : trailing      #simple(default) | trailing | ATRXX | 
               rate : 6 #-3%
            take_profit:
               enabled: true
               rate: 16 # 10percent
            decision:
               model    : simple
               config   :         
                  strategy: EMA_RSI_SLOW
                  params : {'rsi_bullish_mark': 24, 'buy_pause_time': 12, 'rsi': 40, 'ema_s': 98, 'period': 54, 'sell_pause_time': 52, 'ema_m': 106, 'ema_l': 136, 'ema_ll': 140}
      # products - end
      order_type    : market
      fee     : 
         maker : 0.15 #make fee %
         taker : 0.25 #taker fee %
   #cbpro - end
# exchanges - end

# TODO: exchanges specific config should follow a common timing, should be driven by global config
candle_interval : 300  #300s == 5m 

backfill:
   enabled  : true  
   period   : 3  #in Days

# Global Trading config, applied if product/exch specific policies are not configured
stop_loss:
   enabled: true
   kind : trailing      #simple(default) | trailing | ATRXX | 
   rate : 6 #-3%
  
take_profit:
   enabled: true
   rate: 16 # 10percent

#decision engine
decision:
# model : [ML|simple]
#   model    : ML
#   config   : "config/model/model.hdf5"

   model    : simple
   config   :
      #strategy: TRIX_RSI
      #params : {'rsi_oversold_level': 66, 'period': 76, 'trix': 10, 'rsi': 24, 'rsi_overbought_level': 78}
      strategy: EMA_DEV
      params : {'ema_sell_s': 85, 'timeout_sell': 14, 'rsi': 24, 'treshold_pct_buy_l': 1.0, 'ema_buy_s': 185, 'timeout_buy': 14, 'period': 165, 'treshold_pct_sell_s': 0.92, 'ema_buy_l': 70, 'treshold_pct_sell_l': 1.35, 'treshold_pct_buy_s': 0.39, 'ema_sell_l': 25}
      #strategy : EMA_RSI
      #params : {'rsi_bullish_mark': 36, 'rsi': 14, 'ema_s': 84, 'period': 124, 'ema_m': 180, 'ema_l': 152, 'ema_ll': 126}
      #strategy: EMA_RSI_SLOW
      #params : {'rsi_bullish_mark': 24, 'buy_pause_time': 12, 'rsi': 40, 'ema_s': 98, 'period': 54, 'sell_pause_time': 52, 'ema_m': 106, 'ema_l': 136, 'ema_ll': 140}
      #Hall of Fame
      #EMA_RSI: {'rsi': 64, 'ema_s': 44, 'period': 38, 'ema_m': 184, 'ema_l': 156, 'ema_ll': 64}
      #EMA_DEV{'ema_sell_s': 80, 'rsi': 90, 'treshold_pct_buy_l': 0.23, 'ema_buy_s': 130, 'period': 190, 'ema_sell_l': 85, 'ema_buy_l': 115, 'treshold_pct_sell_l': 1.08, 'treshold_pct_buy_s': 1.02, 'treshold_pct_sell_s': 0.65}
#"MINMAX" #<buy hold
#"EMA_RSI" #<buy-hold, high fail%
#TRIX_RSI" #very low profit
#TREND_BOLLINGER"
#TREND_RSI"
simulator:
   enabled : false

genetic_optimizer: 
   enabled : false
   N_POP : 1000
   N_GEN : 100
   N_MP : 10
   config   :
      strategy : EMA_DEV
      trading : {}
      
ui:
   enabled : false
   port : 8080
   
#EOF
