# Example: YAML file format
#mysql:
#    host: localhost
#    user: root
#    passwd: my secret password
#    db: write-math
#other:
#    preprocessing_queue:
#        - preprocessing.scale_and_center
#        - preprocessing.dot_reduction
#       - preprocessing.connect_lines
#    use_anonymous: yes
##################################################

exchange:
  name        : gdax
  products: 
    - 'BTC-USD':
       - currency:
          - 'BTC'
          - 'USD'
#    - 'ETH-USD':
#       - currency:
#          - 'ETH'
#          - 'USD'
    
  ##### sandbox api base ######
  apiBase      : 'https://api-public.sandbox.gdax.com'
  wsFeed       : 'wss://ws-feed-public.sandbox.gdax.com'
  apiPassphrase: 'vbf2vuem4da'
  apiKey       : '0068fd511915b4f659fcf0513e2f3362'
  apiSecret    : 'rMybWQ2CzcDAl3duxf6H+4d9K+CtR/qtvWIbxY3k/JcyGnqdnGotwabBdvOXCRm56ny+6SNRKn7HjsUrmoh+hg=='
  
  #### LIVE API **** Be careful with these **** ###
#  apiBase     : 'https://api.gdax.com'
#  wsFeed      : 'wss://ws-feed.gdax.com'

  orderType    : limit
  orderFee     : 0
  
  backfill:
    - enabled  : Yes  
    - period   : 3  #in Days
    - granularity: 300  #in Sec    

